# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'Testing Az service principal with read only Access'
    script: |
      # Write your commands here
      
      echo 'Hello world'

      az login --service-principal -u 2f7fa7f2-7bc5-4d08-a819-b7e33792a7a1 -p cMQn.m1StgNqtz09z3x-_-ZTk~i95mfy_p --tenant yaswanth354gmail.onmicrosoft.com
      az group list
      az resource list > sp.json
      cat sp.json

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**/*.json'
    TargetFolder: 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'